version: '3.8'
services:
  cashu-gatewaw-db:
    build: ./docker/postgres
    ports:
      - "5432:5432"
  cashu-gatewaw-rest:
    build:
      context: .
      dockerfile: cashu-gateway-rest/Dockerfile
    depends_on:
      - cashu-gatewaw-db
      - phoenixd
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cashu-gatewaw-db:5432/cashu-gateway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  phoenixd:
    image: acinq/phoenixd:latest
    ports:
      - "9740:9740"
