version: '3.8'
services:
    cashu-gateway-db:
        build: ./docker/postgres
        ports:
            - "5432:5432"
    cashu-gateway-rest:
        build:
            context: .
            dockerfile: cashu-gateway-rest/Dockerfile
        depends_on:
            - cashu-gateway-db
            - phoenixd
            - cashu-gateway-webhook
        ports:
            - "${CASHU_GATEWAY_PORT:-8080}:${CASHU_GATEWAY_PORT:-8080}"
        environment:
            CASHU_GATEWAY_PORT: ${CASHU_GATEWAY_PORT:-8080}
            SPRING_DATASOURCE_URL: jdbc:postgresql://cashu-gateway-db:5432/cashu-gateway
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            WEBHOOK_BASE_URL: http://cashu-gateway-webhook:8080/webhook/phoenixd
    cashu-gateway-webhook:
        build:
            context: .
            dockerfile: cashu-gateway-webhook/Dockerfile
        depends_on:
            - cashu-gateway-rest
        environment:
            # Let the servlet contact the REST API inside the Compose network
            CATALINA_OPTS: -Dgateway.api.base_url=http://cashu-gateway-rest:8080
        ports:
            - "9090:8080"
    phoenixd:
        image: acinq/phoenixd:latest
        ports:
            - "9740:9740"
