phoenixd.currency=sat
phoenixd.expiration=86400
phoenixd.fee.percent=0.004
phoenixd.fee.fixed=4
phoenixd.expiry=60
phoenixd.lnaddress=on
A1b2C3d4.wid=phoenixd

dummy.payment_status=80
dummy.amount=10
dummy.expiry=86400
dummy.fee_reserve=30

webhook.base_url=http://localhost:9090/webhook