phoenixd.currency=sat
phoenixd.expiration=86400
phoenixd.fee.percent=.04
phoenixd.fee.fixed=4
phoenixd.expiry=60
A1b2C3d4.wid=phoenixd

strike.currency=BTC

webhook.base_url=http://localhost:9090/webhook