-- Cash Invoice table for NIP-XX Cash Payments
CREATE TABLE cash_invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref             VARCHAR(24)  NOT NULL UNIQUE,
    ephemeral_pubkey VARCHAR(66) NOT NULL,
    ephemeral_privkey VARCHAR(64) NOT NULL,
    amount          INTEGER      NOT NULL,
    fiat            VARCHAR(3),
    memo            VARCHAR(140),
    proof_code      VARCHAR(6),
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    relay_urls      VARCHAR(1024) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    event_id        VARCHAR(64),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at    TIMESTAMP WITH TIME ZONE,
    intent_received_at TIMESTAMP WITH TIME ZONE,
    paid_at         TIMESTAMP WITH TIME ZONE,
    cancel_reason   VARCHAR(64)
);

CREATE INDEX idx_cashinvoice_ref ON cash_invoice (ref);
CREATE INDEX idx_cashinvoice_ephemeral_pubkey ON cash_invoice (ephemeral_pubkey);
CREATE INDEX idx_cashinvoice_status ON cash_invoice (status);
CREATE INDEX idx_cashinvoice_expires_at ON cash_invoice (expires_at);
