-- Cash Intent table for NIP-XX Cash Payments (kind 5201)
CREATE TABLE cash_intent (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref               VARCHAR(24)  NOT NULL,
    customer_pubkey   VARCHAR(66)  NOT NULL,
    proof             VARCHAR(6),
    customer_timestamp TIMESTAMP WITH TIME ZONE,
    event_id          VARCHAR(64)  NOT NULL UNIQUE,
    received_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    processed         BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_cashintent_ref ON cash_intent (ref);
CREATE INDEX idx_cashintent_customer_pubkey ON cash_intent (customer_pubkey);
CREATE INDEX idx_cashintent_event_id ON cash_intent (event_id);
