-- Cash Receipt table for NIP-XX Cash Payments (kind 5202)
CREATE TABLE cash_receipt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref             VARCHAR(24)  NOT NULL UNIQUE,
    status          VARCHAR(20)  NOT NULL,
    amount_received INTEGER      NOT NULL,
    confirmed_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    event_id        VARCHAR(64)  NOT NULL UNIQUE,
    published_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_cashreceipt_ref ON cash_receipt (ref);
CREATE INDEX idx_cashreceipt_event_id ON cash_receipt (event_id);
