phoenixd.currency=sat
phoenixd.expiration=86400
phoenixd.fee.percent=0.004
phoenixd.fee.fixed=4
phoenixd.expiry=60
phoenixd.lnaddress=on

webhook.base_url=http://localhost:9090/webhook
phoenixd.base_url=http://phoenixd:9740
